- byoqm/main.py
- pull_request_template.md
Added a file called pull_request_template.md that enables a template on each new pull request.
- [ ✅ ] I have performed a self-review of my code.
- [ ✅ ] If it is a core feature, I have added thorough tests.
- [ ✅ ] Have I requested and notified the boys for review of the pull-request?
> added pr template

- README.md
- byoqm/__init__.py
- byoqm/main.py
- byoqm/models/code_climate.py
- pull_request_template.md
1. Add a bunch of dummy metric methods for CodeClimate in `code_climate.py`
2. Add a path to the source code to inspect as a command line argument to `main.py`
3. Hard-code some metric / aggregation values to get it moving off the ground
> Code climate

- byoqm/models/code_climate.py
- byoqm/models/test/data/many_methods_file.py
- byoqm/models/test/test_code_climate.py
Implemented function to count the amount of methods
> Method count

- byoqm/models/code_climate.py
- byoqm/models/test/method_argument_file.py
- byoqm/models/test/test_code_climate.py
Implemented method to count amount of methods having more than 4 arguments
> Argument count

- .github/workflows/test.yml
Setup poetry in test action using: https://github.com/marketplace/actions/setup-poetry#v5. As well as building the necessary grammar files for tree-sitter to use and run throughout the action
> Add Poetry Run to test.yml

- .gitignore
- byoqm/main.py
- byoqm/models/code_climate.py
- output/2023-02-22.csv
Added creation of csv files. 
VERY basic and needs to be changed later on
> Csv output

- poetry.lock
- pyproject.toml
changed ^3.11 to 3.10 because I can't run treesitter with 3.11 apparently..
- [ ✅ ] I have performed a self-review of my code.
- [ ✅ ] If it is a core feature, I have added thorough tests.
- [ ✅ ] Have I requested and notified the boys for review of the pull-request?
> Changed ^3.11 to ^3.10 in .toml file

- output/2023-02-22.csv
We had a tracked file in a folder that is gitignored
> Rm 2023-02-22.csv Since output is gitignored

- byoqm/models/code_climate.py
- byoqm/models/test/data/complex_logic.py
Bug when having a complex logic statement with call statements as parameters
> Complex logic fix

- byoqm/main.py
- byoqm/models/code_climate.py
- byoqm/visuals/dashboard.py
- byoqm/visuals/line.py
I have not tested the code as this is a change to visualization. I have run the program and seen that I get the expected graphs with the data given in csv files. If you run main on this branch and it shows empty graphs with weird units on the x-axis instead of dates, it is most likely due to differences in the csv file format.
This PR fixes both the date time on bokeh plots and introduces pandas as a way to read csv files.
> Introduce pandas

- byoqm/visuals/dashboard.py
the term 'gridplot' is apparently reserved - changed to gridplots
> gridplot is reserved

- .gitignore
Added /cpd to .gitignore so it does not get pushed to the repo.
- [ 👍🏼 ] I have performed a self-review of my code.
- [ 👍🏼 ] Have I requested and notified the boys for review of the pull-request?
> Added ./metrics/cpd/ to git ignore.

- .gitignore
- byoqm/main.py
- byoqm/runner.py
- byoqm/visuals/dashboard.py
- byoqm/visuals/line.py
- models/code_climate.py
- poetry.lock
Created `runner.py` which is responsible for taking a quality model, executing its metrics and aggregations functions, and producing a .csv file. `runner.py` includes the date/time down to the second as the tile of the .csv file and adds the name of the quality model used to produce the values in the .csv file.
We should merge #34 first, and use that here to skip the qualitymodel=<qualtiymodel> line that is now written to csv.
> Runner module

- byoqm/visuals/dashboard.py
> changed import

- byoqm/source_coordinator/source_coordinator.py
- byoqm/source_coordinator/test/data/a_file.py
- byoqm/source_coordinator/test_source_coordinator.py
source_coordinator somewhat follows the repository design pattern, this is what plugins can use to interact with the source code. Following this, each plugin should be a class that accepts a source_coordinator.
> Add source_coordinator module

- metrics/identical_codeblocks.py
- metrics/similar_codeblocks.py
- metrics/test/data/test_data_similar_codeblocks/data_similar_codeblocks.py
- metrics/test/test_identical_codeblocks.py
- metrics/test/test_similar_codeblocks.py
I have added logic for similar code. Again we use the CPD tool to analyze code for similarities. I have added 2 flags to cpd that makes it ignore identifiers and literals. That is, when this command of cpd is run it will ignore the constants and variable names as well as values and string contents when comparing text. In my eyes, this should be sufficient enough to say it will compare similarities.
Do note however, that this change doesn't implement the source coordinator that was merged prior, so that it adheres to current flow. It will be changed along with other metrics later.
> Similar code cpd

- byoqm/source_coordinator/test_source_coordinator.py
Added an extra test for checking that the tree created is not empty
> Source coordinator test

- .github/workflows/test.yml
- README.md
- byoqm/build_treesitter.py
- byoqm/main.py
- byoqm/runner/runner.py
- byoqm/runner/test_runner.py
- byoqm/source_coordinator/languages.py
- byoqm/source_coordinator/source_coordinator.py
- byoqm/source_coordinator/test/data/a_nother_file.cs
- byoqm/source_coordinator/test_source_coordinator.py
added support for languages Java and C#. source_coordinator can now find the coherent file extensions to the given language. Please see the read.me for changes with regards to downloading java and c# grammars for tree-sitter
> add support for more languages

- models/code_climate.py
Used findings from running code climate on code to improve on our implementation.
> Rm structrual_issues & More metrics in complexity

- byoqm/runner/runner.py
- byoqm/visuals/dashboard.py
- byoqm/visuals/test_dashboard.py
Added the information of analyzed src_path in .csv output
- [ 👍🏼 ] I have performed a self-review of my code.
- [ 👍🏼 ] Have I requested and notified the boys for review of the pull-request?
> Added source root info in .csv outputs

- byoqm/runner/runner.py
cli option --save-file did not work. That has been fixed
> fixed issue with save-file

- byoqm/source_repository/query_translations.py
- metrics/breaks_in_linear_flow.py
- metrics/test/data/test_data_breaks_in_linear_flow/five_breaks.py
- metrics/test/test_breaks_in_linear_flow.py
This is a metric that will be aggregated into cognitive complexity. It counts up all the occurrences of control flow statements as they break a linear flow. It is intentionally only for python, as I am waiting for monday to proceed with other languages.
> Add Breaks in Linear Flow

- byoqm/source_repository/query_translations.py
- metrics/recursion.py
- metrics/test/data/test_data_recursion/data_recursion.py
- metrics/test/data/test_recursion.py
- metrics/test/test_recursion.py
Write a metric that checks for recursive function calls.
> Recursion metric

- byoqm/dashboard/dashboard.py
Added if-check for edge case of path being ' . '
> Runnable with path '.'

- byoqm/runner/runner.py
The parent folder to our different save locations now gets created if it does not exist
> Fixed generation of primary output folder

- byoqm/dashboard/dashboard.py
Fixed mistake when trying to visualise .gitkeep
> ignored gitkeeps in dashboard

- byoqm/metric/result.py
- byoqm/runner/runner.py
- metrics/argument_count.py
- metrics/cognitive_complexity.py
- metrics/complex_logic.py
- metrics/file_length.py
- metrics/identical_codeblocks.py
- metrics/method_count.py
- metrics/method_length.py
- metrics/nested_controlflows.py
- metrics/return_statements.py
- metrics/similar_codeblocks.py
- metrics/test/test_argument_count.py
- metrics/test/test_cognitive_complexity.py
- metrics/test/test_complex_logic.py
- metrics/test/test_file_length.py
- metrics/test/test_identical_codeblocks.py
- metrics/test/test_method_count.py
- metrics/test/test_method_length.py
- metrics/test/test_nested_controlflows.py
- metrics/test/test_return_statements.py
- metrics/test/test_similar_codeblocks.py
- models/code_climate.py
- models/no_cpd.py
- models/tester_model.py
Changed Result such that the outcome does not only return Integers, but is now generic such that any outcome can be returned. Changed all the metrics to initialize this Result object with the correct values. Changed QMs so that they use the outcome to calculate aggregations instead of the result.get_frequency() that is now deleted.
> Result revamp

- byoqm/dashboard/dashboard.py
- byoqm/main.py
- byoqm/runner/runner.py
- byoqm/runner/test_runner.py
- byoqm/writer/__init__.py
- byoqm/writer/test_writer.py
- byoqm/writer/writer.py
Extracted a writer class from runner to ensure that runner is only in charge of actually running the aggregations.
Also moved the different save functions out into their own functions. 
NOTE: run and _write_to_csv could probably be merged - I would love to hear your thoughts
> Extracted a writer class from runner

- .gitignore
- byoqm/main.py
- byoqm/runner/runner.py
- byoqm/writer/writer.py
- models/code_climate.py
> fixed problem in main and added logging

- README.md
- pyproject.toml
I have implemented the changes suggested by Helge.
Note that this will change our 'main' command to 'modu':
```sh
poetry run modu <path> <QM>
```
> Feedback fixes

- figures/line.py
- metrics/identical_codeblocks.py
Configured the graphs such that they will match the highest y-value, thus getting all the information present.
Added  a 10% buffer so it is more clear to see where the top of the line is.
Maintainability throws this off as its not fit for a line graph, therefore we simply don't create a line graph for maintainability. 👍🏼
> Axis ranges

- figures/line.py
- modu/dashboard/dashboard.py
Quick change such that we don't get 'empty graphs' when outcome is 0...
> Extra 0 check

- metrics/identical_codeblocks.py
- metrics/similar_codeblocks.py
This took way longer that it should. I am sorry for not seeing the obvious.
Made it so cpd now inspects all files instead of single files. This should make it capable of finding duplication across the given code base.
> add fix to cpd
